<script type="text/javascript">
//<![CDATA[
    setBoletoSessionId("<?= $this->getBoletoSession();?>");
    assignBoletoHash();
//]]>
</script>
    
<script type="text/javascript">
//<![CDATA[
var x = document.getElementsByTagName("script");
  var header_already_added = false;
  for (var i=0; i< x.length; i++){
      if (x[i].src == "<?php echo $this->getSkinUrl('uol/pagseguro/js/pagseguro-before-save.js') ?>"){
             header_already_added = true;
      }
  }

  if (header_already_added == false){
    // add header if not already added
    var head = document.getElementsByTagName("head")[0];
    var s = document.createElement('script');
    s.type = 'text/javascript';
    s.src = '<?php echo $this->getSkinUrl('uol/pagseguro/js/pagseguro-before-save.js') ?>';
    head.appendChild(s);
  }
//]]>
</script>

<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <input type="hidden" id="boletoHash" value="" name="payment[boleto_hash]">
    <div class="input-box">
        <label class="required" ><?php echo $this->__('CPF ou CNPJ') ?></label>
            <input 
                class="input-text" 
                id="bilitDocument"  
                onblur="validateDocument(this)" 
                onkeyup="documentMask(this)"
                type="text" 
                title="<?php echo $this->__('CPF ou CNPJ') ?>" 
                name="payment[boleto_cpf]" 
                value="" 
                maxlength="18"
            />
            <div class="display-none validation-advice bilitDocument-error-message">Insira um CPF ou CNPJ válido</div>
    
    <ul class="pagseguro-direct-payment-ul">
        <li>&#9679; Imprima o boleto e pague no banco ou na internet utilizando o seu c&oacute;digo de barras</li>
        <li>&#9679; O prazo de validade do boleto &eacute; de 1 dia &uacute;til</li>
    </ul>

  </div>
    <div>
        <ul class="pagseguro-direct-payment-ul">
            <li>Esta compra está sendo feita no Brasil 
                <img class="flag-origin-country-img" src="<?php echo $this->getSkinUrl('uol/pagseguro/images/flag-origin-country.png'); ?>">
            </li>
        </ul>
    </div>
</div>
