<script type="text/javascript">
    setCreditCardSessionId("<?= $this->getCreditCardSession(); ?>");
    assignCreditCardHash();
</script>

<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <form>
    <input type="hidden" id="creditCardHash" value="" name="payment[credit_card_hash]">
    <input type="hidden" id="creditCardToken" value="" name="payment[credit_card_token]">
    
    <input type="hidden" id="creditCardBrand">
    <input type="hidden" id="creditCardInstallment" name="payment[credit_card_installment]">
    <input type="hidden" id="creditCardInstallmentValue" name="payment[credit_card_installment_value]">
    <input type="hidden" id="grand_total" value="<?= $this->getGrandTotal() ?>">

    <div class="pagseguro-label-spacing">
        <label for="creditCardNum">Número do cartão</label>
        <span>
            <input type="number" id="creditCardNum" required onblur="getBrand(this)">
            <span class="pagseguro-display-none help-block creditCardNum-error-message">Insira um número de cartão válido</span>
        </span>
    </div>

    <div class="pagseguro-label-spacing">
        <label for="creditCardHolder">Nome impresso no cartão</label>
        <span>
            <input name="payment[credit_card_holder]" id="creditCardHolder" required onblur="validateCardHolder(this)" minlength="3">
            <span class="pagseguro-display-none help-block creditCardHolder-error-message">Insira um nome</span>
        </span>
    </div>
    
    <div class="pagseguro-label-spacing">
        <label for="creditCardExpirationMonth">Validade</label>
        <span>
            <select id="creditCardExpirationMonth" title="Cartão válido até" required>
                <option value="" disabled selected>Mês</option>
                <option value="01">01</option>
                <option value="02">02</option>
                <option value="03">03</option>
                <option value="04">04</option>
                <option value="05">05</option>
                <option value="06">06</option>
                <option value="07">07</option>
                <option value="08">08</option>
                <option value="09">09</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
            </select>
            <span class="pagseguro-display-none help-block creditCardExpirationMonth-error-message">Escolha um mês</span>
        </span>
        <span>
            <select id="creditCardExpirationYear" title="Cartão válido até" required>
                <option value="" disabled selected>Ano</option>
                <?php
                $year = idate("Y");
                $maxYear = $year + 20;
                for ($i = $year; $i < $maxYear; $i++): ?>
                    <option value="<?= $i; ?>"><?= $i; ?></option>
                <?php endfor; ?>
            </select>
            <span class="pagseguro-display-none help-block creditCardExpirationYear-error-message">Escolha um ano</span>
        </span>
    </div>

    <div class="pagseguro-label-spacing">
        <label for="creditCardCode">Código de segurança</label>
        <span>
            <input class="form-control code-card-mask" id="creditCardCode" type="number" minlength="3"
                   maxlength="4"
                   onblur="validateCreditCardCode(this)" required>
            <span class="pagseguro-display-none help-block creditCardCode-error-message">Insira um código segurança válido</span>
        </span>
    </div>
    
    <div class="pagseguro-label-spacing">
        <label><?php echo $this->__('CPF ou CNPJ') ?>*</label>
        <span>
            <input onblur="validateDocument(this)" type="number" title="<?php echo $this->__('CPF ou CNPJ') ?>" name="payment[credit_card_cpf]" value="" />
            <span style="display:none;" class="pagseguro-display-none help-block creditCardDocument-error-message">Insira um CPF ou CNPJ válido</span>
        </span>
    </div>

    <div class="pagseguro-label-spacing">
        <label for="creditCardHolderBirthdate">Data de nascimento</label>
        <span>
            <input name="payment[credit_card_holder_birthdate]" class="form-control date-mask" id="creditCardHolderBirthdate" required
                   placeholder="dd/mm/aaaa" onblur="validateCreditCardHolderBirthdate(this)">
            <span class="pagseguro-display-none help-block creditCardHolderBirthdate-error-message">Insira uma data de nascimento válida</span>
        </span>
    </div>

    <div class="pagseguro-label-spacing">
        <label class="col-xs-12 col-sm-2 col-sm-offset-2 control-label"
               for="card_installments">Parcelas</label>
        <span>
            <select id="card_installment_option" title="Nº de parcelas" required
                    disabled onchange="cardInstallmentOnChange(this.value)">
                <option value="null" disabled selected>Escolha o N° de parcelas</option>
            </select>
            <span class="pagseguro-display-none help-block card_installment_option-error-message">Escolha uma opção de parcelamento</span>
        </span>
    </div>

    <div class="credit-total pagseguro-label-spacing">
        <label for="card_installments">Total</label>
        <span>
            <span id="card_total">selecione o número de parcelas</span>
        </span>
    </div>
    
    <div>
        <ul style="padding: 0.9em 0em 0.1em; font-size: smaller; font-style: italic">
            <li>Esta compra está sendo feita no Brasil 
                <img style="position: absolute; padding-left: 0.5em; display: inline" src="<?php echo $this->getSkinUrl('uol/pagseguro/images/flag-origin-country.png'); ?>">
            </li>
        </ul>
    </div>
    </form>
</div>

        
    
    
