<script type="text/javascript">
//<![CDATA[
    setOnlineDebitSessionId("<?= $this->getOnlineDebitSession();?>");
    assignOnlineDebitHash();
//]]>
</script>

<script>
//<![CDATA[
    var x = document.getElementsByTagName("script");
      var header_already_added = false;
    for (var i=0; i< x.length; i++){
      if (x[i].src == "<?php echo $this->getSkinUrl('uol/pagseguro/js/pagseguro-before-save.js') ?>"){
             header_already_added = true;
      }
  }

  if (header_already_added == false){
    // add header if not already added
    var head = document.getElementsByTagName("head")[0];
    var s = document.createElement('script');
    s.type = 'text/javascript';
    s.src = '<?php echo $this->getSkinUrl('uol/pagseguro/js/pagseguro-before-save.js') ?>';
    head.appendChild(s);
  }
//]]>
</script>
 
<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <input type="hidden" id="onlineDebitHash" value="" name="payment[online_debit_hash]">
    <input type="hidden" id="onlineDebitBankName" value="" name="payment[online_debit_bank_name]">
    
    
    <div style="float: left">
        <div class="pagseguro-boleto-label-div">
            <label class="pagseguro-required"><?php echo $this->__('CPF ou CNPJ') ?>*</label>
        </div>
        <div class="pagseguro-cc-input-div">
            <input 
                id="debitDocument"
                class="input-text"
                onblur="validateDocument(this)"
                onkeydown="documentMask(this)"
                type="text"
                title="<?php echo $this->__('CPF ou CNPJ') ?>"
                name="payment[online_debit_cpf]"
                value=""
                maxlength="18"
            />
            <div class="display-none validation-advice debitDocument-error-message">Insira um CPF ou CNPJ válido</div>
        </div>
    <div class="input-box">
        <label class="required" style="padding: 0.9em 0em 0em;"><?php echo $this->__('Selecione abaixo seu banco') ?></label>
        <div style="padding: 0em 1em;">
            <div>
                <div>
                    <label>
                        <input class="input-radio" type="radio" id="debitbankName" name="debitbankName" value="itau"
                               required onclick="validateDebitBankName(this)">
                        Itaú
                    </label>
                </div>
            </div>
            <div>
                <div>
                    <label>
                        <input class="input-radio" type="radio" id="debitbankName" name="debitbankName" value="bradesco"
                               required onclick="validateDebitBankName(this)">
                        Bradesco
                    </label>
                </div>
            </div>
            <div>
                <div>
                    <label>
                        <input class="input-radio" type="radio" id="debitbankName" name="debitbankName" value="banrisul"
                               required onclick="validateDebitBankName(this)">
                        Banrisul
                    </label>
                </div>
            </div>
            <div>
                <div>
                    <label>
                        <input class="input-radio" type="radio" id="debitbankName" name="debitbankName"
                               value="bancodobrasil" onclick="validateDebitBankName(this)">
                        Banco do Brasil
                    </label>
                </div>
            </div>
        </div>
    </div>
    <div class="display-none validation-advice debitbankName-error-message">Escolha um banco</div>
    <div style="display: inline-block; "class="pagseguro-label-spacing pagseguro-cc-group-div">
        <ul class="pagseguro-direct-payment-ul">
            <div class="pagseguro-cc-input-div">
                <li>Esta compra está sendo feita no Brasil 
                    <img class="flag-origin-country-img" src="<?php echo $this->getSkinUrl('uol/pagseguro/images/flag-origin-country.png'); ?>">
                </li>
            </div>
        </ul>
    </div>
</div>
