<?php
/**
************************************************************************
Copyright [2014] [PagSeguro Internet Ltda.]

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
************************************************************************
*/
?>

<div class="page-head">
    <h2 class="sub-title">Finalizando sua compra com PagSeguro</h2>
</div>
<script type="text/javascript" src="https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.lightbox.js"></script>
<script type="text/javascript">
<?php $paymentData = $this->getConvertCode();?>
    function checkout(payment)
    {
        PagSeguroLightbox(
        '<?php echo $paymentData['code'] ?>',{
            success: function(token){
            	window.location.href = "<?php echo Mage::getUrl('checkout/onepage/success', array('_secure' => true));?>";
            },
            abort: function(){
            	window.location.href = '<?php echo $paymentData['urlCompleta'] ?>';
            }
        });
    }
</script>

<table style="width:100%;">
    <tr>
        <td style="width:100%">
            
            Sua compra est&aacute; em processo de finaliza&ccedil;&atilde;o, aguarde um estante.<br />
            Caso a p&aacute;gina de finaliza&ccedil;&atilde;o de pagamento n&atilde;o se inicie automaticamente, <a href="<?php echo $paymentData['urlCompleta']?>" id="redirect">Clique Aqui</a>
            <script type="text/javascript">
            checkout();
            </script>
        </td>
    </tr>
</table>
