<?php

/**
 ************************************************************************
 * Copyright [2015] [PagSeguro Internet Ltda.]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ************************************************************************
 */

?>


<?php $lastOrder = Mage::getModel('sales/order')
    ->loadByIncrementId(Mage::getSingleton('checkout/session')->getLastRealOrderId())->getEntityId(); ?>

<div class="page-title pagseguro-payment-retry-title">
    <h1 class="center">Sua transação não foi concluída</h1>
</div>

<p class="pagseguro-payment-retry-p">Ocorreu um erro ao processar a transação.</p>

<div class="pagseguro-payment-retry-button-set button-set">
    <a type="button" class="button" href="<?= Mage::getBaseUrl() . 'sales/order/reorder/order_id/' . $lastOrder ?>">
        <span><span>TENTAR NOVAMENTE</span></span></a>
    <a type="button" class="button" href="<?= Mage::getBaseUrl() ?>">
        <span><span>VOLTAR PARA LOJA</span></span></a>
</div>
