<?php

/**
************************************************************************
Copyright [2015] [PagSeguro Internet Ltda.]

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
************************************************************************
*/
$_customer = Mage::getSingleton('customer/session')->getCustomer();
$orders = Mage::getResourceModel('sales/order_collection')
->addFieldToSelect('*')
->addFieldToFilter('customer_id', $_customer->getId())
->addAttributeToSort('created_at', 'DESC')
->setPageSize(1);
?>

<div class="page-head">
    <h2 class="sub-title">Ocorreu um erro durante o processamento da sua compra. Caso o erro persista, entre em contato com a loja</h2>
</div>

<table style="width:100%;">
    <tr>
        <td style="width:100%">
            Ocorreu um erro ao realizar a transação com o PagSeguro.<br /><br />
            <?php if($orders->getFirstItem()->getId()):?>
              <a href="<?php echo Mage::getUrl(''); ?>sales/order/reorder/order_id/<?php echo $orders->getFirstItem()->getId() ?>/" class="link-reorder button btn btn-success">
                  <span><span>Tentar novamente</span></span>
              </a>
            <?php endif;?>
        </td>
    </tr>
</table>
