<div class="page-head">
    <h2 class="sub-title">Finalizando sua compra com PagSeguro</h2>
</div>
<script type="text/javascript">
    window.onload = function () {
        window.open('<?= Mage::registry('link') ?>', '_blank');
    };
</script>
<table style="width:100%;">
    <tr>
        <td style="width:100%">
            Sua compra está em processo de finalização, aguarde um instante.<br>
            Se a página de pagamento não abrir automaticamente
            <a href="<?= Mage::registry('link') ?>" target="_blank">clique aqui</a>.
        </td>
    </tr>
</table>
