<?php

/**
************************************************************************
Copyright [2014] [PagSeguro Internet Ltda.]

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
************************************************************************
*/

?>
<?php Mage::helper('pagseguro/abandoned')->checkAbandonedAccess(); ?>

<img class="pagseguro_logo" src="<?php echo $this->getSkinUrl('uol/pagseguro/images/logo.png'); ?>" />

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <th><h3><?php echo $this->__('Abandonadas'); ?></h3></th>
        </tr>
    </table>
</div>

<p>
	<?php 
		$string .= 'Com esta funcionalidade, você poderá listar as transações abandonadas e disparar, manualmente, ';
		$string .= 'um e-mail para seu comprador. Este e-mail conterá um link que o redirecionará para o fluxo de ';
		$string .= 'pagamento, exatamente no ponto onde ele parou.';
		echo $this->__($string);
	 ?>
</p>

<form action="javascript:void(0)" method="post" >
	<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey();?>" />
    <input type="submit" class="pagseguro-button green-theme normal btnSearch" value="<?php echo $this->__('Pesquisar');?>">
    <input type="submit" class="pagseguro-button green-theme normal btnSend" value="<?php echo $this->__("Enviar selecionados");?>">
</form>

<?php $days = Mage::getSingleton('UOL_PagSeguro_Model_PaymentMethod')->getConfigData('abandoned_link'); ?>

<table id="htmlgrid" class="grid" border="0" cellpadding="10" cellspacing="10" width="100%">
	<thead>
		<tr>
			<th class="select_checkbox" onclick="checkedAll()" width="10%"><?php echo $this->__('Selecionar');?></th>
			<th width="25%"><?php echo $this->__('Data do Pedido');?></th>
			<th width="20%"><?php echo $this->__('ID Magento');?></th>
			<th width="25%"><?php echo $this->__('Data de Expiração');?></th>
			<th width="10%"><?php echo $this->__('Enviar e-mail');?></th>
			<th width="10%"><?php echo $this->__('Detalhes');?></th>
		</tr>
	</thead>
	<tbody>
		
	</tbody>
</table>

<?php 
	$noTransaction = $this->__('Nenhum resultado.');
	$noEmailSelected = $this->__("Selecione pelo menos um campo da coluna 'Enviar'.");
	$emailSendSuccess = $this->__("E-mail enviado com sucesso!");
	$emailsSendSuccess = $this->__("E-mails enviado com sucesso!");
?>

<script type="text/javascript">	
	var i = 0;
		
	jQuery(document).ready(function(){					     
		var flow = 0;
		var totalRows = 0;	
		var page = 0;
		var currentPage = 0;
		var oTable;		
		
		// Initiates the creation of the table dataTable
		jQuery('#htmlgrid').dataTable({	
			"info": false,
			"lengthChange": false,
			"searching": false,
			"bStateSave": true,
			"pageLength": 10,
   			"aaSorting": [[ 1, "desc" ]],
			"aoColumnDefs": [
				{ 'bSortable': false, 'aTargets': [ 0, 4, 5 ] },
				{ "sClass": "tabela", 'aTargets': [ 1, 2, 3, 4, 5 ] }
			],
			
			// Creates paging and notifies when there is no record
			"oLanguage": {
				"sEmptyTable":"<?php echo $this->__($noTransaction); ?>",
				"oPaginate": {
					"sNext": '<?php echo $this->__('Próximo');?>',
					"sLast": '<?php echo $this->__('Último');?>',
					"sFirst": '<?php echo $this->__('Primeiro');?>',
					"sPrevious": '<?php echo $this->__('Anterior');?>'
				}
			},		
			
			// Every interaction with the table it is called
			"fnDrawCallback": function(oSettings) {	
				// Makes when clicked on a registry is redirected to the editing order of Magento	
				trHoverClick();	
				oTable = this;
				totalRows = oTable.fnGetData().length;
				var table = jQuery('#htmlgrid').DataTable();
				var info = table.page.info();
				//oTable.fnSort( [ [1,'asc'] ] );
				if (totalRows > 1) {
					jQuery('.btnSend').fadeIn('slow');
				} else {
					jQuery('.chk_email input').attr('disabled','disabled');
				}
				// Only if greater than 10 records show paging
				if (totalRows > 10) {					
					jQuery('.dataTables_paginate').css('display','block');
					flow = 1;					
				} else {									
					jQuery('.dataTables_paginate').css('display','none');
					flow = 0;
				}
				
				// If the home page does not display the previous page button
				if (info.page == 0) {
					jQuery('a#htmlgrid_previous').css('display','none');
				}			
				
				// If the last page does not display the next page button
				if ((info.page+1) == info.pages) {
					jQuery('a#htmlgrid_next').css('display','none');
				}	
				
				i++;
				
				// Stores which is the page that appears after update				
				if (i == 1) { 
					currentPage = page;	
				}	
				
				// Stores the current page, calculated by number of records and number of records per page					
				page  = Math.ceil(oSettings._iDisplayStart / oSettings._iDisplayLength);					
			},
			
			// When it completes assembly of the table is executed
			"initComplete": function (oSettings) {				
		        oTable = this;		        
		        if (currentPage != 0) {
		        	// When upgraded back on the page that was
		        	oTable.fnPageChange(currentPage);	
		        }	        
		    }
		});
		
		jQuery(".btnSearch").on("click",function() {
			var converted = '';
			blockModal(1);
			jQuery.ajax({
                url: "<?php echo Mage::getSingleton('adminhtml/url')->getUrl('pagseguro/adminhtml_ajax'); ?>",
                type: "POST",
                data: { 
                		form_key: "<?php echo Mage::getSingleton('core/session')->getFormKey();?>", 
                		origin: 'abandoned'
                	  },
                success: function(result) { 
                	i = 0;  
                	// handle the return of ajax and dates back to table    	
                    if (result != "") {
						converted = JSON.parse(result);
                        jQuery('#htmlgrid').dataTable().fnClearTable(true);           
                        jQuery('#htmlgrid').dataTable().fnAddData(converted);
                        jQuery('#htmlgrid').dataTable()._fnInitComplete();  
                    } else {
                    	jQuery('.btnSend').fadeOut('slow');
                    }
                    //After reassembling the table removes the modal of loading
                    blockModal(0);
                    
                },
                error: function() {
                	// Remove the modal of loading
                    blockModal(0);
                }
             });
		});
		jQuery(".btnSend").on("click",function() {
			var ckbFalse = 0;
			var j = 0;
			jQuery('input[name="send_emails[]"]').each(function() {
				if (jQuery(this).is(':checked') == false) {
					ckbFalse++;
				}
				j++;
			});	
			if (j == ckbFalse) {
				jQuery('#messages').empty();					
				setMsgError("<?php echo $this->__($noEmailSelected); ?>");
			} else {
				jQuery('#messages').empty();
				var config = '';
		    	var id = '';
		    	var recovery = '';
		    	var jsonArr = [];
		    	var count = 0;
		    	
		    	jQuery('input[name="send_emails[]"]').each(function() {
					if (jQuery(this).is(':checked') == true) {
							count++;
							config = jQuery(this).data('config').split('/');
							jsonArr.push({
						        id: config[0],
						        recovery: config[1]
						    });
		        			
					}
					    
			    });	
			    var msg	= '';
			    if (count == 1) {
			    	msg = '<?php echo " " . $this->__($emailSendSuccess); ?>';
			    }  else {
			    	msg = count + '<?php echo " " . $this->__($emailsSendSuccess); ?>';
			    } 
		    	var converted = '';
				blockModal(1);
				jQuery.ajax({
	                url: "<?php echo Mage::getSingleton('adminhtml/url')->getUrl('pagseguro/adminhtml_ajax'); ?>",
	                type: "POST",
	                data: { 
	                		form_key: "<?php echo Mage::getSingleton('core/session')->getFormKey();?>", 
	                		json: jsonArr,
	                		origin: 'abandoned'	                		
	                	  },
	                success: function(result) {    	
	                    if (result == 'run') {
	                    	jQuery('input[name="send_emails[]"]').prop('checked','');
	                    	jQuery('#messages').empty();					
							setMsgSuccess(msg);
		                }
	                    //After reassembling the table removes the modal of loading
	                    blockModal(0);
	                    
	                },
	                error: function() {
	                	// Remove the modal of loading
	                    blockModal(0);
	                }
	             });
			}
		}); 		
    });    
    
    function SendMail(data) {    	
		var config = jQuery(data).data('config').split('/');
    	var id = config[0];
    	var recovery = config[1];
    	var jsonArr = [];
    	jsonArr.push({
	        id: id,
	        recovery: recovery
	    });		    
    	var converted = '';
		blockModal(1);
		jQuery.ajax({
            url: "<?php echo Mage::getSingleton('adminhtml/url')->getUrl('pagseguro/adminhtml_ajax'); ?>",
            type: "POST",
            data: { 
            		form_key: "<?php echo Mage::getSingleton('core/session')->getFormKey();?>", 
            		origin: 'abandoned',
            		json: jsonArr
            	  },
            success: function(result) {     	
                if (result == 'run') {
                	jQuery('input[name="send_emails[]"]').prop('checked','');
                	jQuery('#messages').empty();					
					setMsgSuccess("<?php echo $this->__($emailSendSuccess); ?>");
                }
                //After reassembling the table removes the modal of loading
                blockModal(0);
                
            },
            error: function() {
            	// Remove the modal of loading
                blockModal(0);
            }
         });
    }   
    
    // Create the modal of load and remove this
    function blockModal(block) {     	   		
		if (block == 1) {
		    jQuery.blockUI({
		        message: '<h1><?php echo $this->__('Carregando');?>' +
		        		 	'<img src="<?php echo $this->getSkinUrl('uol/pagseguro/images/loading.gif'); ?>" />' + 
		        		 '</h1>',
		        css: {
		            border: 'none',
		            padding: '15px',
		            backgroundColor: '#4f7743',
		            'border-radius': '10px',
		            '-webkit-border-radius': '10px',
		            '-moz-border-radius': '10px',
		            opacity: 0.7,
		            color: '#90e874'
		        },
		        overlayCSS: { backgroundColor: 'gray' }
		    });
		    		    
		} else {
		    setTimeout(jQuery.unblockUI, 1000);
		}
	}
</script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('uol/pagseguro/js/pagseguro.js');?>"></script>