<?php

/**
************************************************************************
Copyright [2015] [PagSeguro Internet Ltda.]

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
************************************************************************
*/

?>

<?php
	Mage::helper('pagseguro/conciliation')->checkConciliationAccess();
	$_SESSION['days'] = 0;	
?>

<img class="pagseguro_logo" src="<?php echo $this->getSkinUrl('uol/pagseguro/images/logo.png'); ?>" />

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <th><h3><?php echo $this->__('Conciliação'); ?></h3></th>
        </tr>
    </table>
</div>

<p>
	<?php 
		$string .= 'Esta consulta permite obter as transações recebidas por você em um intervalo de datas. ';
		$string .= 'Ela pode ser usada periodicamente para verificar se o seu sistema recebeu todas as notificações ';
		$string .= 'de transações enviadas pelo PagSeguro, de forma a conciliar as transações armazenadas ';
		$string .= 'em seu sistema com o PagSeguro.';
		echo $this->__($string);
	 ?>
</p>

<form action="javascript:void(0)" method="post" >
	<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey();?>" />
	<label><?php echo $this->__('Dias'); ?></label>
	<select id='pagseguro_dias_btn' name='pagseguro_dias' class="select">
        <option value='5'>5</option>
        <option value='10'>10</option>
        <option value='15'>15</option>
        <option value='20'>20</option>
        <option value='25'>25</option>
        <option value='30'>30</option>
    </select>
    <input type="submit" class="pagseguro-button green-theme normal btnSearch" value="<?php echo $this->__('Pesquisar');?>">
    <input type="submit" class="pagseguro-button green-theme normal btnConciliation" value="<?php echo $this->__("Conciliar");?>">
</form>

<table id="htmlgrid" class="grid" border="0" cellpadding="10" cellspacing="10" width="100%">
	<thead>
		<tr>
			<th class="select_checkbox" onclick="checkedAll()" width="10%"><?php echo $this->__('Selecionar');?></th>
			<th width="12%"><?php echo $this->__('Data do Pedido');?></th>
			<th width="10%"><?php echo $this->__('ID Magento');?></th>
			<th width="22%"><?php echo $this->__('ID PagSeguro');?></th>
			<th width="16%"><?php echo $this->__('Status Magento');?></th>
			<th width="16%"><?php echo $this->__('Status PagSeguro');?></th>
			<th width="14%"><?php echo $this->__('Pedido');?></th>
		</tr>
	</thead>
</table>

<?php
	$tooltip .= 'Somente serão exibidas transações criadas após a instalação do módulo em sua versão 2.3. ';
	$tooltip .= 'Transações criadas antes desta versão não serão exibidas.';
	$noTransaction = 'Nenhum resultado.';	
	$noTransactionSelected = $this->__("Selecione pelo menos um campo da coluna 'Selecionar'.");
	$transactionSuccess = $this->__("Transação conciliada com sucesso!");
	$transactionsSuccess = $this->__("Transações conciliadas com sucesso!");
?>

<p class="info"><?php echo $this->__('Não encontra suas transações antigas?'); ?> 
    <a data-tooltip="<?php echo $this->__($tooltip); ?>">
        <img alt="ajuda" src="<?php echo $this->getSkinUrl('uol/pagseguro/images/help.png'); ?>">
    </a>
</p>

<script type="text/javascript">	
	var i = 0;	
		
	jQuery(document).ready(function(){   				     
		var flow = 0;
		var totalRows = 0;	
		var page = 0;
		var currentPage = 0;
		var oTable;			
		
		// Initiates the creation of the table dataTable
		jQuery('#htmlgrid').dataTable({			
			"info": false,
			"lengthChange": false,
			"searching": false,
			"bStateSave": true,
			"pageLength": 10,
			"aaSorting": [[ 1, "desc" ]],
			"aoColumnDefs": [
				{ 'bSortable': false, 'aTargets': [ 0, 6] },
				{ "sClass": "tabela", 'aTargets': [ 1, 2, 3, 4, 5, 6 ] }
			],
			
			// Creates paging and notifies when there is no record
			"oLanguage": {
				"sEmptyTable":"<?php echo $this->__($noTransaction); ?>",
				"oPaginate": {
					"sNext": '<?php echo $this->__('Próximo');?>',
					"sLast": '<?php echo $this->__('Último');?>',
					"sFirst": '<?php echo $this->__('Primeiro');?>',
					"sPrevious": '<?php echo $this->__('Anterior');?>'
				}
			},
			
			// If the status of Magento and PagSeguro are different, added a color
			"fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {				
				if ( aData[3] != aData[4]){
					jQuery(nRow).addClass('red')
				}				
			},
			
			// Every interaction with the table it is called
			"fnDrawCallback": function(oSettings) {	
				// Makes when clicked on a registry is redirected to the editing order of Magento	
				trHoverClick();
				oTable = this;
				totalRows = oTable.fnGetData().length;
				var table = jQuery('#htmlgrid').DataTable();
				var info = table.page.info();
				
				// Only if greater than 10 records show paging
				if (totalRows > 10) {					
					jQuery('.dataTables_paginate').css('display','block');
					flow = 1;					
				} else {									
					jQuery('.dataTables_paginate').css('display','none');
					flow = 0;
				}
				
				// If the home page does not display the previous page button
				if (info.page == 0) {
					jQuery('a#htmlgrid_previous').css('display','none');
				}			
				
				// If the last page does not display the next page button
				if ((info.page+1) == info.pages) {
					jQuery('a#htmlgrid_next').css('display','none');
				}	
				
				i++;
				
				// Stores which is the page that appears after update				
				if (i == 1) { 
					currentPage = page;	
				}	
				
				// Stores the current page, calculated by number of records and number of records per page					
				page  = Math.ceil(oSettings._iDisplayStart / oSettings._iDisplayLength);					
			},
			
			// When it completes assembly of the table is executed
			"initComplete": function (oSettings) {				
		        oTable = this;
		        
		        if (currentPage != 0) {
		        	// When upgraded back on the page that was
		        	oTable.fnPageChange(currentPage);	
		        }	        
		    }
		});		
		
		// Executes when the search button clicked
        jQuery(".btnSearch").on("click",function(){         	      	
        	var getDays = jQuery('#pagseguro_dias_btn').find(":selected").text();
        	var converted = '';
        	// calls the modal of loading
        	blockModal(1);
        	
            jQuery.ajax({
                url: "<?php echo Mage::getSingleton('adminhtml/url')->getUrl('pagseguro/adminhtml_ajax'); ?>",
                type: "POST",
                data: { 
                		form_key: "<?php echo Mage::getSingleton('core/session')->getFormKey();?>", 
                		days: getDays,
                		origin: 'conciliation'
                	  },
                success: function(result) {   
                	// handle the return of ajax and dates back to table    	
	                if (result == "run") {
						jQuery('#htmlgrid').dataTable().fnClearTable(true);
	                } else {
	                	converted = JSON.parse(result);
	                    jQuery('#htmlgrid').dataTable().fnClearTable(true);           
	                    jQuery('#htmlgrid').dataTable().fnAddData(converted);
	                    jQuery('#htmlgrid').dataTable()._fnInitComplete();
	                }	       
                    //After reassembling the table removes the modal of loading
                    blockModal(0);
                    
                },
                error: function() {
                	// Remove the modal of loading
                    blockModal(0);
                }
			});				
		});
		
		jQuery(".btnConciliation").on("click",function() {			
			var ckbFalse = 0;
			var j = 0;
			jQuery('input[name="conciliation_orders[]"]').each(function() {
				if (jQuery(this).is(':checked') == false) {
					ckbFalse++;					
				}
				j++;
			});	
			if (j == ckbFalse) {
				jQuery('#messages').empty();					
				setMsgError("<?php echo $this->__($noTransactionSelected); ?>");
			} else {
				jQuery('#messages').empty();
				var config = '';
		    	var id = '';
		    	var code = '';
		    	var status = '';
		    	var jsonArr = [];
		    	var count = 0;
		    	
		    	jQuery('input[name="conciliation_orders[]"]').each(function() {
					if (jQuery(this).is(':checked') == true) {
							count++;
							config = jQuery(this).data('config').split('/');
							jsonArr.push({
						        id: config[0],
						        code: config[1],
						        status: config[2]
						    });        			
					}
					    
			    });	
			    var msg	= '';
			    if (count == 1) {
			    	msg = '<?php echo " " . $this->__($transactionSuccess); ?>';
			    }  else {
			    	msg = count + '<?php echo " " . $this->__($transactionsSuccess); ?>';
			    } 
		    	var converted = '';
				blockModal(1);
				jQuery.ajax({
	                url: "<?php echo Mage::getSingleton('adminhtml/url')->getUrl('pagseguro/adminhtml_ajax'); ?>",
	                type: "POST",
	                data: { 
	                		form_key: "<?php echo Mage::getSingleton('core/session')->getFormKey();?>", 
	                		json: jsonArr,
	                		origin: 'conciliation'	                		
	                	  },
	                success: function(result) { 
	                    i = 0;
		            	// handle the return of ajax and dates back to table    	
		                if (result == "run") {
							jQuery('#htmlgrid').dataTable().fnClearTable(true);
		                	jQuery('#messages').empty();					
							setMsgSuccess(msg);
		                } else {
		                	converted = JSON.parse(result);
		                    jQuery('#htmlgrid').dataTable().fnClearTable(true);           
		                    jQuery('#htmlgrid').dataTable().fnAddData(converted);
		                    jQuery('#htmlgrid').dataTable()._fnInitComplete();
		                    jQuery('#messages').empty();					
							setMsgSuccess(msg);
		                }	                
		                //After reassembling the table removes the modal of loading
		                blockModal(0);
	                    
	                },
	                error: function() {
	                	// Remove the modal of loading
	                    blockModal(0);
	                }
	             });
			}
		});
							
    });
    
    // Create the modal of load and remove this
    function blockModal(block) {     	   		
		if (block == 1) {
		    jQuery.blockUI({
		        message: '<h1><?php echo $this->__('Carregando');?>' +
		        		 	'<img src="<?php echo $this->getSkinUrl('uol/pagseguro/images/loading.gif'); ?>" />' + 
		        		 '</h1>',
		        css: {
		            border: 'none',
		            padding: '15px',
		            backgroundColor: '#4f7743',
		            'border-radius': '10px',
		            '-webkit-border-radius': '10px',
		            '-moz-border-radius': '10px',
		            opacity: 0.7,
		            color: '#90e874'
		        },
		        overlayCSS: { backgroundColor: 'gray' }
		    });
		    		    
		} else {
		    setTimeout(jQuery.unblockUI, 1000);
		}
	}
</script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('uol/pagseguro/js/pagseguro.js');?>"></script>