<?php

/**
************************************************************************
Copyright [2015] [PagSeguro Internet Ltda.]

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
************************************************************************
*/

?>

<?php
	Mage::helper('pagseguro/conciliation')->checkConciliationAccess();
	$_SESSION['days'] = 0;	
?>

<div id="pagseguro-module">
	
    <div id="pagseguro-module-header">
		<div class="wrapper">
			
			<div id="pagseguro-logo">
				<img class="pagseguro_logo" src="<?php echo $this->getSkinUrl('uol/pagseguro/images/logo.png'); ?>" />
				<div id="pagseguro-module-version">Versão <?php echo Mage::getConfig()->getModuleConfig("UOL_PagSeguro")->version; ?></div>
			</div>
		    
		    <a id="pagseguro-registration-button" class="pagseguro-button gray-theme" href="https://pagseguro.uol.com.br/registration/registration.jhtml?ep=7&tipo=cadastro#!vendedor" target="_blank"><?php echo $this->__('Faça seu cadastro'); ?></a>

		</div>
	</div>

	<div id="pagseguro-module-content">

		<div class="wrapper">
		    
		    <div id="pagseguro-module-menu">
			    
			    <ul>
			    	<li 
						id="menu-item-config"
						data-has-form="true">
						<a href="<?php echo Mage::getSingleton('adminhtml/url')->getUrl('adminhtml/system_config/edit/section/payment/key'); ?>">Configuração</a>
					</li>
					<li 
						id="menu-item-conciliation"
						class="selected" 
						data-has-form="true">
						<a href="<?php echo Mage::getSingleton('adminhtml/url')->getUrl('pagseguro/adminhtml_conciliation'); ?>">Conciliação</a>
					</li>
					<li 
						id="menu-item-abandoned"
						data-has-form="true">
						<a href="<?php echo Mage::getSingleton('adminhtml/url')->getUrl('pagseguro/adminhtml_abandoned'); ?>">Abandonadas</a>
					</li>
					<li 
						id="menu-item-required" 
						data-has-form="true">
						<a href="<?php echo Mage::getSingleton('adminhtml/url')->getUrl('pagseguro/adminhtml_requirements'); ?>">Requisitos</a>
					</li>
			    </ul>
			</div>

		    <div id="pagseguro-module-contents">


				<h2 class="title" title="Conciliação"><?php echo $this->__('Conciliação'); ?></h2>

				<p>
					<?php 
						$string .= 'Esta consulta permite obter as transações recebidas por você em um intervalo de datas. ';
						$string .= 'Ela pode ser usada periodicamente para verificar se o seu sistema recebeu todas as notificações ';
						$string .= 'de transações enviadas pelo PagSeguro, de forma a conciliar as transações armazenadas ';
						$string .= 'em seu sistema com o PagSeguro.';
						echo $this->__($string);
					 ?>
				</p>

				<div class="pagseguro-search-tools">
					<form action="javascript:void(0)" method="post" >
						<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey();?>" />
						<input type="submit" class="pagseguro-button" id="conciliation-search-button" value="<?php echo $this->__('Pesquisar');?>">
						<select class="pagseguro-field" id="pagseguro-conciliation-days-input" name="pagseguro_dias">
					        <option value='5'>5</option>
					        <option value='10'>10</option>
					        <option value='15'>15</option>
					        <option value='20'>20</option>
					        <option value='25'>25</option>
					        <option value='30'>30</option>
					    </select>
						<label><?php echo $this->__('últimos dias'); ?></label>
					    <div class="right-tools">
						    	<input type="submit" class="pagseguro-button" id="conciliation-button" value="<?php echo $this->__("Conciliar");?>" disabled>
						</div>
					    
					</form>
				</div>

				<table id="conciliation-table" class="pagseguro-table">
					<thead>
						<tr>
							<th class="select_checkbox" width="3%" onclick="checkboxes();">
								<input type="checkbox" id="pagseguro-check-all" />
							</th>
							<th width="9%"><?php echo $this->__('Data');?></th>
							<th width="11%"><?php echo $this->__('ID Magento');?></th>
							<th width="30%"><?php echo $this->__('ID PagSeguro');?></th>
							<th width="15%"><?php echo $this->__('Status Magento');?></th>
							<th width="20%"><?php echo $this->__('Status PagSeguro');?></th>
							<th width="11%"><?php echo $this->__('Pedido');?></th>
						</tr>
					</thead>
				</table>

				<?php
					$noTransaction = 'Nenhum resultado.';	
					$noTransactionSelected = $this->__("Selecione pelo menos um campo da coluna 'Selecionar'.");
					$transactionSuccess = $this->__("Transação conciliada com sucesso!");
					$transactionsSuccess = $this->__("Transações conciliadas com sucesso!");
				?>

				<div id="conciliation-info" class="pagseguro-msg pagseguro-msg-info pagseguro-msg-micro">
			        <p><?php echo $this->__('Somente transações geradas a partir da versão 2.3 do módulo serão listadas.'); ?></p>
			    </div>


			</div>
		</div>
	</div>
</div>

<script type="text/javascript">	
	var i = 0;	
		
	jQuery(document).ready(function(){   				     
		
		Menu.init();
		PageConciliation.init();		
							
    });

    var PageConciliation = new function(){

		var requestTransactions = function() {
			var getDays = jQuery('#pagseguro-conciliation-days-input').find(":selected").text();
        	var converted = '';
        	// calls the modal of loading
        	Modal.showLoading();
        	
            jQuery.ajax({
                url: "<?php echo Mage::getSingleton('adminhtml/url')->getUrl('pagseguro/adminhtml_ajax'); ?>",
                type: "POST",
                data: { 
                		form_key: "<?php echo Mage::getSingleton('core/session')->getFormKey();?>", 
                		days: getDays,
                		origin: 'conciliation'
                	  },
                success: function(result) {   

                	if (result == "[HTTP 401] - UNAUTHORIZED") {
                		
        				Modal.message('error', "[HTTP 401] - Usuário não autorizado.");
        			} else {
                	
	                	// handle the return of ajax and dates back to table    	
		                if (result == "run") {
							jQuery('#conciliation-table').dataTable().fnClearTable(true);
							Modal.message('alert', "Não há transações para conciliação no período.");
		                } else {
		                	converted = JSON.parse(result);
		                    jQuery('#conciliation-table').dataTable().fnClearTable(true);           
		                    jQuery('#conciliation-table').dataTable().fnAddData(converted);
		                    jQuery('#conciliation-table').dataTable()._fnInitComplete();
		                    //After reassembling the table removes the modal of loading
		                    Modal.hideLoading();
		                }	
	                }                   
                },
                error: function(err) {
                	// Remove the modal of loading
                    Modal.hideLoading();
                }
			});	
		}

		var doConciliation = function(){
			var ckbFalse = 0;
			var j = 0;
			jQuery('input[name="conciliation_orders[]"]').each(function() {
				if (jQuery(this).is(':checked') == false) {
					ckbFalse++;					
				}
				j++;
			});	
			if (j == ckbFalse) {
				jQuery('#messages').empty();					
				setMsgError("<?php echo $this->__($noTransactionSelected); ?>");
			} else {
				jQuery('#messages').empty();
				var config = '';
		    	var id = '';
		    	var code = '';
		    	var status = '';
		    	var jsonArr = [];
		    	var count = 0;
		    	
		    	jQuery('input[name="conciliation_orders[]"]').each(function() {
					if (jQuery(this).is(':checked') == true) {
							count++;
							config = jQuery(this).data('config').split('/');
							jsonArr.push({
						        id: config[0],
						        code: config[1],
						        status: config[2]
						    });        			
					}
					    
			    });	
			    var msg	= '';
			    if (count == 1) {
			    	msg = '<?php echo " " . $this->__($transactionSuccess); ?>';
			    }  else {
			    	msg = count + '<?php echo " " . $this->__($transactionsSuccess); ?>';
			    } 
		    	var converted = '';
				Modal.showLoading();
				jQuery.ajax({
	                url: "<?php echo Mage::getSingleton('adminhtml/url')->getUrl('pagseguro/adminhtml_ajax'); ?>",
	                type: "POST",
	                data: { 
	                		form_key: "<?php echo Mage::getSingleton('core/session')->getFormKey();?>", 
	                		json: jsonArr,
	                		origin: 'conciliation'	                		
	                	  },
	                success: function(result) { 
	                    i = 0;

		            	// handle the return of ajax and dates back to table    	
		                if (result == "run") {
							jQuery('#conciliation-table').dataTable().fnClearTable(true);
		                	jQuery('#messages').empty();					
		                } else {
		                	converted = JSON.parse(result);

		                    // jQuery('#conciliation-table').dataTable().fnClearTable(true);           
		                    // jQuery('#conciliation-table').dataTable().fnAddData(converted);
		                    // jQuery('#conciliation-table').dataTable()._fnInitComplete();
		                    var oTable = jQuery('#conciliation-table').dataTable();
			                oTable.fnClearTable(false);           
			                oTable.fnAddData(converted, false);
			                oTable.fnStandingRedraw();
		                    jQuery('#messages').empty();					
		                }	 
		                jQuery(':checkbox').prop('checked','');
		                jQuery('#conciliation-button').prop("disabled", true);

		                var successMsg;
		                if (jsonArr.length > 1) {
		                	successMsg = 'Conciliações realizadas com sucesso.'; 
		                } else {
		                	successMsg = 'Conciliação realizada com sucesso.'; 
		                }  
		                Modal.message('success', successMsg);        
	                    
	                },
	                error: function() {
	                     Modal.message('error', 'Não foi possível realizar a conciliação.');
	                }
	             });
			}
		}

		var prepareTable = function(){

			var flow = 0;
			var totalRows = 0;	
			var page = 0;
			var currentPage = 0;
			var oTable;		

			jQuery.fn.dataTableExt.oApi.fnStandingRedraw = function(oSettings) {
			    //redraw to account for filtering and sorting
			    // concept here is that (for client side) there is a row got inserted at the end (for an add)
			    // or when a record was modified it could be in the middle of the table
			    // that is probably not supposed to be there - due to filtering / sorting
			    // so we need to re process filtering and sorting
			    // BUT - if it is server side - then this should be handled by the server - so skip this step
			    if(oSettings.oFeatures.bServerSide === false){
			        var before = oSettings._iDisplayStart;
			        oSettings.oApi._fnReDraw(oSettings);
			        //iDisplayStart has been reset to zero - so lets change it back
			        oSettings._iDisplayStart = before;
			        oSettings.oApi._fnCalculateEnd(oSettings);
			    }
			      
			    //draw the 'current' page
			    oSettings.oApi._fnDraw(oSettings);
			};
			
			// Initiates the creation of the table dataTable
			jQuery('#conciliation-table').dataTable({			
				"info": false,
				"lengthChange": false,
				"searching": false,
				"bStateSave": true,
				"pageLength": 10,
				"aaSorting": [[ 1, "desc" ]],
				"aoColumnDefs": [
					{ 'bSortable': false, 'aTargets': [ 0, 6] },
					{ "sClass": "tabela", 'aTargets': [ 1, 2, 3, 4, 5, 6 ] }
				],
				
				// Creates paging and notifies when there is no record
				"oLanguage": {
					"sEmptyTable":"<?php echo $this->__($noTransaction); ?>",
					"oPaginate": {
						"sNext": '<?php echo $this->__('Próximo');?>',
						"sLast": '<?php echo $this->__('Último');?>',
						"sFirst": '<?php echo $this->__('Primeiro');?>',
						"sPrevious": '<?php echo $this->__('Anterior');?>'
					}
				},
				
				// If the status of Magento and PagSeguro are different, added a color
				"fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {				
					if ( aData[3] != aData[4]){
						jQuery(nRow).addClass('red')
					}				
				},
				
				// Every interaction with the table it is called
				"fnDrawCallback": function(oSettings) {	
					// Makes when clicked on a registry is redirected to the editing order of Magento	
					oTable = this;
					totalRows = oTable.fnGetData().length;
					var table = jQuery('#conciliation-table').DataTable();
					var info = table.page.info();

					//trClick
					if (totalRows >= 1) {
						var href;
						jQuery('#conciliation-table tbody tr').unbind('click');

						jQuery('#conciliation-table tbody tr').bind('click', function () {
							href = jQuery(table.row( this ).data()[6])[0].href;
							jQuery('#conciliation-table tbody').off();
							jQuery('#conciliation-table tbody').on('click', 'td', function () {
								if (jQuery(this).index() != 0 && jQuery(this).index() != 6){
									window.open(href, '_blank');
								}
							} );
						} );

					}

					//Checkbox enable | disable
					jQuery('#conciliation-table tbody input:checkbox').change(function(){

		            	var isChecked = jQuery("#conciliation-table tbody :checked").length;
		          
						if (isChecked > 0) {
							jQuery('#conciliation-button').prop("disabled", false);
						} else {
							jQuery('#conciliation-button').prop("disabled", true);
						}

		            });
					
					// Only if greater than 10 records show paging
					if (totalRows > 10) {					
						jQuery('.dataTables_paginate').css('display','block');
						flow = 1;					
					} else {									
						jQuery('.dataTables_paginate').css('display','none');
						flow = 0;
					}
					
					// If the home page does not display the previous page button
					if (info.page == 0) {
						jQuery('a#conciliation-table_previous').css('display','none');
					}			
					
					// If the last page does not display the next page button
					if ((info.page+1) == info.pages) {
						jQuery('a#conciliation-table_next').css('display','none');
					}	
					
					i++;
					
					// Stores which is the page that appears after update				
					if (i == 1) {
						if (page >= 1 && totalRows < 1) {
							currentPage = page - 1;	
						} else {
							currentPage = page;	
						}
					}	
					
					// Stores the current page, calculated by number of records and number of records per page					
					page  = Math.ceil(oSettings._iDisplayStart / oSettings._iDisplayLength);					
				},
				
				// When it completes assembly of the table is executed
				"initComplete": function (oSettings) {				
			        oTable = this;
			        
			        if (currentPage != 0) {
			        	// When upgraded back on the page that was
			        	oTable.fnPageChange(currentPage);	
			        }	        
			    }
			});	
		}

		this.init = function() {
        	prepareTable();
            jQuery('#conciliation-search-button').click(function () {
                requestTransactions();
            });
            jQuery('#conciliation-button').click(function () {
                doConciliation();
            });
        };
	}

</script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('uol/pagseguro/js/pagseguro.js');?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('uol/pagseguro/js/pagseguro-module.js');?>"></script>
